#define SAMPLES_PER_ORIENTATION 5
#define ORIENTATIONS 12
#define N_INERTIAL_ALIGNMENT ORIENTATIONS*SAMPLES_PER_ORIENTATION
#define N_LASER_CAL 8
#define SAMPLES_PER_READING 25
#define CALIBRATION_STDEV_MIN 0.01
#define N_CALIB_STDEV 5